### ISSUE TITLE
Can you provide the arguments used for the experimental setups?

### ISSUE THREAD

**Issue by AlextheEngineer** [kcyu2014/recurrent-unet#1]
Hi, I'm trying to reproduce the obtained results on various datasets, starting with the EYTH dataset which runs using the proposed recurrent unet. However, there are numerous args missing which doesn't allow me to run the setup you used for your paper. For example, args.unet_level, args.hidden_state (which I assume to be 128 from the paper), args.initial, args.structure. And this is only 1 model on 1 dataset...can you provide more information on the specific setups for the models you used for the paper "Recurrent U-Net for resource-constrained segmentation"? Thanks!

**Comment by kcyu2014** [comment]
Hi Alex,

Sorry for my late reply, recent days are a bit busy for me 😄 

I am going to dig out the code from my side and upload them to the repo as soon as possible, please ping me if you did not hear anything until this Friday.

Best,
Kc

**Comment by kcyu2014** [comment]
After a quick look at the previous files, the settings should be the following: 

For the DRU or SRU
```
--gate=3 # Dual Gate
--gate=2 # Single Gate
```

For hidden state size, we use `hidden_state=128`
For UNet level, DRU(4) means `unet_level=4`
For initialization, simply use `initial=1`  
`args.structure` is not used anymore, I will remove this config later.

Another important setting is `args.feature_scale`, set it to `4` for all hand segmentation tasks, as this will reduce the UNet backbone by `1/args.feature_scale`, setting to 4 means the initial channel of UNet is 32/4= 8.

Hope this helps!

**Comment by tenres** [comment]
Hi kcyu2014, seems like another input is missing, args.recurrent_level (used in class RecurrentUNetCell(nn.Module); line: self.gru_level = args.recurrent_level). I guess we just specify this in main like the above?
